---
# Prepare database maintenance
- hosts:
    - dbservers
    - local
  vars:
    ansible_user: root
  become: true
  tasks:
    - name: "Backup database"
      mysql_db:
        name: "{{ magento_db_name }}"
        state: dump
        target: "/tmp/{{ ansible_hostname }}_{{ ansible_date_time.date }}.sql"
      tags:
        - db-maintenance
        - db-backup
    - name: "Compress database backup"
      command: "gzip /tmp/{{ ansible_hostname }}_{{ ansible_date_time.date }}.sql"
      tags:
        - db-maintenance
        - db-backup

    - name: "Check if database backup exists"
      stat:
        path: "/tmp/{{ ansible_hostname }}_{{ ansible_date_time.date }}.sql.gz"
      register: db_exists
      tags:
        - db-maintenance
        - db-backup

    - debug:
        var: db_exists.stat.exists
      tags:
        - db-maintenance
        - db-backup

    - name: "Show database backup size"
      command: "du -h /tmp/{{ ansible_hostname }}_{{ ansible_date_time.date }}.sql.gz"
      register: db_size
      tags:
        - db-maintenance
        - db-backup
    - debug:
        var: db_size.stdout
      tags:
        - db-maintenance
        - db-backup

    - name: Download the exported database to our local machine
      fetch:
        src: "/tmp/{{ ansible_hostname }}_{{ ansible_date_time.date }}.sql.gz"
        dest: "/tmp/"
        # flat: yes
        fail_on_missing: yes
      register: fetch_backup
      tags:
        - fetch-db-backup
    - debug:
        var: fetch_backup
      tags:
        - fetch-db-backup
