#!/usr/bin/env bash
set -o errexit -o pipefail
# Magento specific DB dump script

# Change the DB name
DB_NAME=$(hostname)
VERSION=$(date +"%d%m_%H-%M")
DUMPS='/tmp/dumps'
OLDEST=$(ls -t "${DUMPS}/${DB_NAME}"_*.sql.gz | tail -n 1)

mkdir -p $DUMPS

show_dumps() {
  ls -lht "${DUMPS}"
}

echo "Making dump:"
mysqldump --defaults-extra-file="${HOME}/.config/my.cfg" "${DB_NAME}" \
  --single-transaction --triggers |
  sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/' |
  gzip >"${DUMPS}/${DB_NAME}_${VERSION}".sql.gz

echo
echo "Files in Dumps folder:"

show_dumps

# Delete oldest file in Dumps folder
echo
echo "Deleting the oldest dump $OLDEST"
rm -f $OLDEST

echo
echo "Size of the latest dump:"
du -h "${DUMPS}/${DB_NAME}_${VERSION}".sql.gz

echo "Exit code: $?"
