name: "Shellcheck"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $ADM_ENV > scripts/admin/.env

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./scripts"
          format: tty
      - name: Run Shell Linter
        uses: azohra/shell-linter@latest
        with:
          path: "./scripts"
