name: "Shellcheck"

on:
  push:
    paths:
      - "scripts/**"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $ADM_ENV > scripts/admin/.env
      - uses: actions/upload-artifact@v3
        with:
          name: scripts-artifact
          path: scripts

  shellcheck:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: scripts-artifact
          path: scripts
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./scripts"
          check_together: 'yes'
          format: tty

  shell_lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: scripts-artifact
          path: scripts
      - name: Run Shell Linter
        uses: azohra/shell-linter@latest
        with:
          path: "./scripts"
